title: ember-cli-page-object
email: kudgo.test@gmail.com
description: >
  Represent the screens of your web app as a series of objects. This ember-cli
  addon eases the construction of these objects on your acceptance tests. Works
  with every version of Ember.
baseurl: "/ember-cli-page-object/"
url: "http://ro0gr.github.io/"
twitter_username: ro0gr
github_username: ro0gr
exclude: ["bower_components", "tmp", "node_modules", "tmp_docs"]

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
